multipart:
    max-file-size: 100Mb
    max-request-size: 100Mb

spring:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    datasource: 
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:backup
      username: sa
      password: 
      platform: h2